#include "Game.hpp"

namespace CTRPluginFramework
{
    const ID_Data Buildings[205] =
	{
		{ "Player 1 House", 0 }, 
		{ "Player 2 House", 1 },
		{ "Player 3 House", 2 },
		{ "Player 4 House", 3 },
		{ "Player 1 Mailbox", 4 },
		{ "Player 2 Mailbox ", 5 },
		{ "Player 3 Mailbox ", 6 },
		{ "Player 4 Mailbox ", 7 },
		{ "Villager 1 House", 8 },
		{ "Villager 2 House", 9 },
		{ "Villager 3 House", 0xA },
		{ "Villager 4 House", 0xB },
		{ "Villager 5 House", 0xC },
		{ "Villager 6 House", 0xD },
		{ "Villager 7 House", 0xE },
		{ "Villager 8 House", 0xF },
		{ "Villager 9 House", 0x10 },
		{ "Villager 10 House", 0x11 },
		{ "Invalid Villa. 1 House", 0x42 },
		{ "Invalid Villa. 2 House", 0x43 },
		{ "Invalid Villa. 3 House", 0x44 },
		{ "Invalid Villa. 4 House", 0x45 },
		{ "Invalid Villa. 5 House", 0x46 },
		{ "Invalid Villa. 6 House", 0x47 },
		{ "Invalid Villa. 7 House", 0x48 },
		{ "Invalid Villa. 8 House", 0x49 },
		{ "Invalid Villa. 9 House", 0x4A },
		{ "Invalid Villa. 10 House", 0x4B },
		{ "Modern Police Station", 0x4C },
		{ "Classic Police Station", 0x4D },
		{ "Cafe", 0x4E },
		{ "Reset Center", 0x4F },
		{ "Classic Town Hall", 0x50 },
		{ "Zen Town Hall", 0x51 },
		{ "FairyTale Town Hall", 0x52 },
		{ "Modern Town Hall", 0x53 },
		{ "Classic Train Station", 0x54 },
		{ "Zen Train Station", 0x55 },
		{ "FairyTale Train Station", 0x56 },
		{ "Modern Train Station", 0x57 },
		{ "Recycle Shop", 0x58 },
		{ "Town Plaza", 0x59 },
		{ "Railroad Crossing Arms", 0x5A },
		{ "Bulletin Board", 0x5B },
		{ "Island Storage Bin", 0x5C },
		{ "Kappn's Boat", 0x5D },
		{ "Katrina's Tent", 0x5E },
		{ "Camper's Tent", 0x5F },
		{ "Redd's Tent", 0x60 },
		{ "Chip's Tent", 0x61 },
		{ "Nat's Tent", 0x62 },
		{ "Franklin's Table", 0x63 },
		{ "Pavé's Dance Stage", 0x64 },
		{ "Countdown Board", 0x65 },
		{ "Redd's Stand", 0x66 },
		{ "Dream World Bed", 0x67 },
		{ "Dock", 0x68 },
		{ "Island Hut", 0x69 },
		{ "Lloid", 0x6A },
		{ "FCS New Years Day", 0x6B },
		{ "FCS Lunar New Year", 0x6C },
		{ "FCS Great Full Moon", 0x6D },
		{ "FCS Groundhog Day ", 0x6E },
		{ "FCS Bean Day", 0x6F },
		{ "FCS Girl's Festival", 0x70 },
		{ "FCS Shamrock Day", 0x71 },
		{ "FCS Arbor Day", 0x72 },
		{ "FCS Nature Day", 0x73 },
		{ "FCS Boy's Festival", 0x74 },
		{ "FCS Teachers' Day", 0x75 },
		{ "FCS Summer Solstice", 0x76 },
		{ "FCS Starcrossed Day", 0x77 },
		{ "FCS Obon", 0x78 },
		{ "FCS Labor Day", 0x79 },
		{ "FCS Autumn Moon JPN&KOR", 0x7A },
		{ "FCS Autumn Moon USA&EUR", 0x7B },
		{ "FCS Explorer's Day", 0x7C },
		{ "FCS Naughty-or-Nice Day", 0x7D },
		{ "FCS Winter Solstice", 0x7E },
		{ "Camping Car 1", 0x7F },
		{ "Camping Car 2", 0x80 },
		{ "Fortune Shop", 0x81 },
		{ "Dream Suite", 0x82 },
		{ "Club LOL", 0x83 },
		{ "Museum", 0x84 },
		{ "Nookling Stores", 0x85 },
		{ "Gardening Store", 0x86 },
		{ "Kicks", 0x87 },
		{ "Shampoodle", 0x88 },
		{ "Able Sis. (Mabel&Sable)", 0x89 },
		{ "Able Sis. (Labelle)", 0x8A },
		{ "Nook's Homes", 0x8B },
		{ "Post Office", 0x8C },
		{ "Photo Booth", 0x8D },
		{ "Main Street lamp", 0x8E },
		{ "Main Street Bench", 0x8F },
		{ "Cobblestone B. (N-S)", 0x90 },
		{ "Cobblestone B. (SW-NE)", 0x91 },
		{ "Cobblestone B. (NW-SE)", 0x92 },
		{ "Cobblestone B. (W-E)", 0x93 },
		{ "Suspension B. (N-S)", 0x94 },
		{ "Suspension B. (SW-NE)", 0x95 },
		{ "Suspension B. (NW-SE)", 0x96 },
		{ "Suspension B. (W-E)", 0x97 },
		{ "Brick B. (N-S)", 0x98 },
		{ "Brick B. (SW-NE)", 0x99 },
		{ "Brick B. (NW-SE)", 0x9A },
		{ "Brick B. (W-E)", 0x9B },
		{ "Modern B. (N-S)", 0x9C },
		{ "Modern B. (SW-NE)", 0x9D },
		{ "Modern B. (NW-SE)", 0x9E },
		{ "Modern B. (W-E)", 0x9F },
		{ "Zen B. (N-S)", 0xA0 },
		{ "Zen B. (SW-NE)", 0xA1 },
		{ "Zen B. (NW-SE)", 0xA2 },
		{ "Zen B. (W-E)", 0xA3 },
		{ "Fairy Tale B. (N-S)", 0xA4 },
		{ "Fairy Tale B. (SW-NE)", 0xA5 },
		{ "Fairy Tale B. (NW-SE)", 0xA6 },
		{ "Fairy Tale B. (W-E)", 0xA7 },
		{ "Yellow Bench", 0xA8 },
		{ "Blue Bench", 0xA9 },
		{ "Wood Bench", 0xAA },
		{ "Metal Bench", 0xAB },
		{ "Log Bench", 0xAC },
		{ "Modern Bench", 0xAD },
		{ "FairyTale Bench", 0xAE },
		{ "Zen Bench", 0xAF },
		{ "Flower Bed", 0xB0 },
		{ "Water Fountain", 0xB1 },
		{ "Instrument Shelter", 0xB2 },
		{ "Sandbox", 0xB3 },
		{ "Garbage Can", 0xB4 },
		{ "Pile of Pipes", 0xB5 },
		{ "Water Well", 0xB6 },
		{ "Fountain", 0xB7 },
		{ "Tire Toy", 0xB8 },
		{ "Jungle Gym", 0xB9 },
		{ "Park Clock", 0xBA },
		{ "Modern Clock", 0xBB },
		{ "FairyTale Clock", 0xBC },
		{ "Zen Clock", 0xBD },
		{ "Street Lamp", 0xBE },
		{ "Round Streetlight", 0xBF },
		{ "Streetlight", 0xC0 },
		{ "Modern Streetlight", 0xC1 },
		{ "FairyTale Streetlight", 0xC2 },
		{ "Zen Streetlight", 0xC3 },
		{ "Balloon Arch", 0xC4 },
		{ "Flower Arch", 0xC5 },
		{ "Campsite", 0xC6 },
		{ "Picnic Blanket", 0xC7 },
		{ "Hammock", 0xC8 },
		{ "Fire Pit", 0xC9 },
		{ "Camping Cot", 0xCA },
		{ "Outdoor Chair", 0xCB },
		{ "Torch", 0xCC },
		{ "Zen Garden", 0xCD },
		{ "Hot Spring", 0xCE },
		{ "Geyser", 0xCF },
		{ "Statue Fountain", 0xD0 },
		{ "Stone Tablet", 0xD1 },
		{ "Water Pump", 0xD2 },
		{ "Wisteria Trellis", 0xD3 },
		{ "Bell", 0xD4 },
		{ "Zen Bell", 0xD5 },
		{ "Scarecrow", 0xD6 },
		{ "Race of Rice", 0xD7 },
		{ "Fence", 0xD8 },
		{ "Bus Stop", 0xD9 },
		{ "Fire Hydrant", 0xDA },
		{ "Traffic Signal", 0xDB },
		{ "Custom-Design Sign", 0xDC },
		{ "Face-Cutout Standee", 0xDD },
		{ "Caution Sign", 0xDE },
		{ "Do-Not-Enter Sign", 0xDF },
		{ "Yield Sign", 0xE0 },
		{ "Cube Sculpture", 0xE1 },
		{ "Archway Sculpture", 0xE2 },
		{ "Chair Sculpture", 0xE3 },
		{ "Illuminated Heart", 0xE4 },
		{ "Illuminated Arch", 0xE5 },
		{ "Illuminated Clock", 0xE6 },
		{ "Illuminated Tree", 0xE7 },
		{ "Stadium Light", 0xE8 },
		{ "Video Screen", 0xE9 },
		{ "Drilling Rig", 0xEA },
		{ "Parabolic Antenna", 0xEB },
		{ "Solar Panels", 0xEC },
		{ "Wind Turbine", 0xED },
		{ "Windmill", 0xEE },
		{ "Lighthouse", 0xEF },
		{ "Tower", 0xF0 },
		{ "Stonehenge", 0xF1 },
		{ "Totem Pole", 0xF2 },
		{ "Moai Statue", 0xF3 },
		{ "Pyramid", 0xF4 },
		{ "Sphinx", 0xF5 },
		{ "Circle Topiary", 0xF6 },
		{ "Square Topiary", 0xF7 },
		{ "Tulip Topiary", 0xF8 },
		{ "Flower Clock", 0xF9 },
		{ "Campground Fence Lock 1", 0xFA },
		{ "Campground Fence Lock 2", 0xFB },
		{ "Empty Space", 0xFC }
	};

	const ID_Data Rooms[109] =
	{
		{ "Town", 0 },
		{ "Main Street", 1 },
		{ "Train Station", 2 },
		{ "Player 1 Main Room", 3 },
		{ "Player 1 Upstairs", 4 },
		{ "Player 1 Basement", 5 },
		{ "Player 1 Right Room", 6 },
		{ "Player 1 Left Room", 7 },
		{ "Player 1 Top Room", 8 },
		{ "Player 2 Main Room", 9 },
		{ "Player 2 Upstairs", 0xA },
		{ "Player 2 Basement", 0xB },
		{ "Player 2 Right Room", 0xC },
		{ "Player 2 Left Room", 0xD },
		{ "Player 2 Top Room", 0xE },
		{ "Player 3 Main Room", 0xF },
		{ "Player 3 Upstairs", 0x10 },
		{ "Player 3 Basement", 0x11 },
		{ "Player 3 Right Room", 0x12 },
		{ "Player 3 Left Room", 0x13 },
		{ "Player 3 Top Room", 0x14 },
		{ "Player 4 Main Room", 0x15 },
		{ "Player 4 Upstairs", 0x16 },
		{ "Player 4 Basement", 0x17 },
		{ "Player 4 Right Room", 0x18 },
		{ "Player 4 Left Room", 0x19 },
		{ "Player 4 Top Room", 0x1A },
		{ "Villager 1 House", 0x1B },
		{ "Villager 2 House", 0x1C },
		{ "Villager 3 House", 0x1D },
		{ "Villager 4 House", 0x1E },
		{ "Villager 5 House", 0x1F },
		{ "Villager 6 House", 0x20 },
		{ "Villager 7 House", 0x21 },
		{ "Villager 8 House", 0x22 },
		{ "Villager 9 House", 0x23 },
		{ "Villager 10 House", 0x24 },
		{ "Camping Grounds", 0x25 },
		{ "Town Hall", 0x26 },
		{ "Retail", 0x2B },
		{ "Nat's Tent", 0x2C },
		{ "Bug-Off Ceremony", 0x2D },
		{ "Chip's Tent", 0x2E },
		{ "Fishing Tourney Ceremony", 0x2F },
		{ "Police Station (Modern)", 0x30 },
		{ "Police Station (Classic)", 0x31 },
		{ "The Roost Café", 0x32 },
		{ "Working In The Roost Café", 0x33 },
		{ "Reset Centre", 0x34 },
		{ "Redd's Tent", 0x35 },
		{ "Katrina's Tent", 0x36 },
		{ "Katrina's Main Street Shop", 0x37 },
		{ "Nook's Cranny", 0x38 },
		{ "T&T Mart", 0x39 },
		{ "Super T&T", 0x3A },
		{ "TIY", 0x3B },
		{ "T&T Emporium - Ground Floor", 0x3C },
		{ "T&T Emporium - Floor 1", 0x3D },
		{ "T&T Emporium - Floor 2", 0x3E },
		{ "Able Sisters - Mable & Sable", 0x3F },
		{ "Able Sisters - Labelle", 0x40 },
		{ "Nook's Homes", 0x41 },
		{ "Kick's (Shoe Shop)", 0x42 },
		{ "Gardening Store (Initial)", 0x43 },
		{ "Gardening Store (Joint w/ TIY)", 0x44 },
		{ "Club LOL", 0x45 },
		{ "Club LOL Night Disco", 0x46 },
		{ "Club LOL Saturday Night (K.K. Songs)", 0x47 },
		{ "Shampoodle", 0x48 },
		{ "Museum - Ground Floor", 0x49 },
		{ "Fish Gallery - Main Room", 0x4A },
		{ "Fish Gallery - North West Room", 0x4B },
		{ "Fish Gallery - North East Room", 0x4C },
		{ "Bug Gallery - Main Room", 0x4D },
		{ "Bug Gallery - North East Room", 0x4E },
		{ "Bug Gallery - North West Room", 0x4F },
		{ "Fossil Gallery - Main Room", 0x50 },
		{ "Fossil Gallery - South Room", 0x51 },
		{ "Fossil Gallery - North West Room", 0x52 },
		{ "Art Gallery - Main Room", 0x53 },
		{ "Art Gallery - East Room", 0x54 },
		{ "Museum - 1st Floor", 0x55 },
		{ "Museum Exhibit - North West", 0x56 },
		{ "Museum Exhibit - South West", 0x57 },
		{ "Museum Exhibit - North East", 0x58 },
		{ "Museum Exhibit - South East", 0x59 },
		{ "Post Office", 0x5A },
		{ "Dream Suite", 0x5B },
		{ "Photo Booth", 0x5C },
		{ "Island Shack (Tour Desk)", 0x67 },
		{ "Island", 0x68 },
		{ "Happy Home Showcase Entrance", 0x8E },
		{ "Happy Home Showcase North Section", 0x8F },
		{ "Happy Home Showcase East Section", 0x90 },
		{ "Happy Home Showcase West Section", 0x91 },
		{ "Model House Main Room", 0x92 },
		{ "Model House Upstairs", 0x93 },
		{ "Model House Basement", 0x94 },
		{ "Model House Right Room", 0x95 },
		{ "Model House Left Room", 0x96 },
		{ "Model House Top Room", 0x97 },
		{ "Desert Island Escape Minigame", 0x9D },
		{ "Puzzle League Minigame", 0x9E },
		{ "Campground - West", 0x9F },
		{ "Campground - East", 0xA0 },
		{ "Camping Car A", 0xA1 },
		{ "Camping Car B", 0xA2 },
		{ "Move Furniture Like AC:HHD Tutorial", 0xA3 },
		{ "Amiibo Camera", 0xA4 }
	};

	const ID_Data Musics[1] =
	{
		{ "", 0 },
	};
}